name: Publish images
permissions: {}
on:
  push:
    tags:
      - "v*"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish-images-cortex:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    outputs:
      container-digest: ${{ steps.publish.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Extract Version"
        id: extract_version
        run: |
          GIT_TAG=${GITHUB_REF##*/}
          VERSION=${GIT_TAG##v}
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - name: Publish with KO
        id: publish
        uses: peak-scale/github-actions/make-ko-publish@a441cca016861c546ab7e065277e40ce41a3eb84 # v0.2.0
        with:
          makefile-target: ko-publish-cortex
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository_owner }}
          version: ${{ steps.extract_version.outputs.version }}
          sign-image: true
          sbom-name: cortex-proxy
          sbom-repository: ghcr.io/${{ github.repository_owner }}/observability-tenancy/cortex-proxy
          signature-repository: ghcr.io/${{ github.repository_owner }}/observability-tenancy/cortex-proxy
          main-path: ./cmd/cortex-proxy/
        env:
          REPOSITORY: ${{ github.repository }}
  generate-provenance-cortex:
    needs: publish-images-cortex
    permissions:
      id-token: write   # To sign the provenance.
      packages: write   # To upload assets to release.
      actions: read     # To read the workflow path.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ghcr.io/${{ github.repository_owner }}/observability-tenancy/cortex-proxy
      digest: "${{ needs.publish-images-cortex.outputs.container-digest }}"
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}


  publish-images-loki:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    outputs:
      container-digest: ${{ steps.publish.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: "Extract Version"
        id: extract_version
        run: |
          GIT_TAG=${GITHUB_REF##*/}
          VERSION=${GIT_TAG##v}
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2
      - name: Publish with KO
        id: publish
        uses: peak-scale/github-actions/make-ko-publish@a441cca016861c546ab7e065277e40ce41a3eb84 # v0.2.0
        with:
          makefile-target: ko-publish-loki
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository_owner }}
          version: ${{ steps.extract_version.outputs.version }}
          sign-image: true
          sbom-name: loki-proxy
          sbom-repository: ghcr.io/${{ github.repository_owner }}/observability-tenancy/loki-proxy
          signature-repository: ghcr.io/${{ github.repository_owner }}/observability-tenancy/loki-proxy
          main-path: ./cmd/loki-proxy/
        env:
          REPOSITORY: ${{ github.repository }}
  generate-provenance-loki:
    needs: publish-images-loki
    permissions:
      id-token: write   # To sign the provenance.
      packages: write   # To upload assets to release.
      actions: read     # To read the workflow path.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.1.0
    with:
      image: ghcr.io/${{ github.repository_owner }}/observability-tenancy/loki-proxy
      digest: "${{ needs.publish-images-loki.outputs.container-digest }}"
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}
